### ISSUE TITLE
Heroku complaining about deprecated stack

### ISSUE THREAD

**Issue by latazzajones** [bmoreonrails/bmoreonrails.org#26]
Until this is resolved no one can update the site - which is a bummer. We're on Ceder-10 and we need to migrate to Ceder-14 
https://devcenter.heroku.com/articles/cedar-14-migration

**Comment by kbladow** [comment]
@latazzajones We did this migration at STAQ. Super easy when you have access.

**Comment by latazzajones** [comment]
@kbladow ya - I know it's not difficult but I'm a little overwhelmed right now with the rails workshop and mentoring. I was hoping someone else would pick it up but I'll try to take care of it at the next hack night if no one else takes it on.

**Comment by kbladow** [comment]
@latazzajones If I had access, I do it for you.

**Comment by latazzajones** [comment]
:heart: @nerdEd might be able to take care of that :)

**Comment by nerdEd** [comment]
@kbladow added to all the things

**Comment by latazzajones** [comment]
@kbladow I took care of this. Thanks again for reaching out :)
