### ISSUE TITLE
Homepage doesn't list upcoming meetups

### ISSUE THREAD

**Issue by alimi** [bmoreonrails/bmoreonrails.org#30]
1. Go to bmoreonrails.org
1. Go to calendar
1. No meetups

See screenshot
![screen shot 2016-05-23 at 10 45 09 pm](https://cloud.githubusercontent.com/assets/772925/15490682/39c376fa-2138-11e6-8859-090e311d1b87.png)

As Jackie Chan
When I visit bmoreonrails.org
I expect to see upcoming meetups

**Comment by jjulian** [comment]
Maybe the meetup.com api changed?

**Comment by latazzajones** [comment]
@jjulian possibly ... but @alimi and I were digging around and it looks like the update_meetups job stopped running a couple months ago. The meetup url still works.

**Comment by latazzajones** [comment]
fixed in https://github.com/bmoreonrails/bmoreonrails.org/commit/61cb4d48d9a73976e304dc247cba35475eb1a68b 
Woot!! Woot!!

**Comment by alimi** [comment]
![young-jackie-chan-thumbs-up-smile-gif](https://cloud.githubusercontent.com/assets/772925/16436242/34b22d20-3d6a-11e6-972d-9d163952213c.gif)
