### ISSUE TITLE
Unable to fetch new Meetups

### ISSUE THREAD

**Issue by alimi** [bmoreonrails/bmoreonrails.org#47]
New Meetups aren't showing up on the homepage because we can't get them from the Meetup API. The rake task that fetches new Meetups calls `Meetup::update` and it fails because `Meetup::UPCOMING_EVENTS_URL` is no longer authorized.

It looks like `Meetup::UPCOMING_EVENTS_URL` was setup using [Meetup's API Key Signature](https://www.meetup.com/meetup_api/auth/#keysign). I think we should be able to generate a new URL, but I'm not sure how/why the existing URL became invalid. I don't see anything about them expiring 🤷🏾‍♂️

**Comment by BSierakowski** [comment]
@alimi check out this pr: https://github.com/bmoreonrails/bmoreonrails.org/pull/48. I made a new signed URL using my meetup API key, not sure if there's any reason why it should use a maintainers API key, but, I also don't use the meetup API for anything, so I'd be happy to stash my API key in the heroku config if that could be helpful in the future.

Either way, this should do the trick!
